# Generated by Django 5.1.2 on 2024-12-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Date and time when the DAG should start.')),
                ('interval', models.CharField(choices=[('daily', 'Daily'), ('hourly', 'Hourly'), ('weekly', 'Weekly')], help_text='Defines the schedule interval for the DAG.', max_length=50)),
                ('kpi_id', models.IntegerField(help_text='ID of the KPI to be used.')),
            ],
        ),
    ]
