# Generated by Django 5.1.2 on 2024-12-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulator',
            name='interval',
            field=models.CharField(choices=[('secondly', 'Secondly'), ('minutely', 'Minutely'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], help_text='Defines the schedule interval for the DAG.', max_length=50),
        ),
    ]
